#!/bin/bash

virtualenv --clear --download ~/venv

source ~/venv/bin/activate

pip install \
    jupyter \
    isort \
    black \
    jupyterlab_code_formatter \
    pandas \
    matplotlib \
    seaborn \
    plotnine \
    plotly \
    dash \
    streamlit \
    statsmodels \
    scikit-learn \
    xgboost \
    prophet
